runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: project3/index.html
  upload: project3/index.html
  
  - url: /
  static_files: project3/style.css
  upload: project3/style.css

- url: /(.*)
  static_files: project3/\1
  upload: project3/(.*)
